### ISSUE TITLE
Docker address

### ISSUE THREAD

**Issue by ViniciusHass** [Treinamento-Stefa-IA-DevOps/treinamento-dia-04-08-eulucasilva#1]
Boa tarde @eulucasilva  **Lucas**,

Você esta conseguindo rodar seu docker com o endereço 127.0.0.1?

**Comment by eulucasilva** [comment]
Opa, boa tarde! Eu não consegui rodar. Estava fazendo isso ontem pela noite e parei para estudar outras coisas. Mas vou voltar a olhar o código e ver o que houve de errado
